### ISSUE TITLE
CUDA error at adaptive_gridsampler_kernel.cu:76 code=209(cudaErrorNoKernelImageForDevice) "cudaGetLastError()"

### ISSUE THREAD

**Issue by bostankhan6** [sunwj/CAR#14]
I get the subject error and then the out image is just black. What can be the issue here?

**Comment by vico4445** [comment]
Hello, I do have the same error. How did you correct it ?

**Comment by supriyaarun27** [comment]
I have the same error. How were you able to fix it?

**Comment by YtengTan** [comment]
Hi, Did u fix this?
