### ISSUE TITLE
VRAM Limitation for High Resolution images

### ISSUE THREAD

**Issue by AbegNext** [sunwj/CAR#2]
Hi @sunwj . Thank you for providing this repository. I was very happy to try it on high-resolution images ( resolution > = 16 Megapixels) and noticed the GPU was running out of memory. I went back and tried it with the benchmark datasets and noticed that images with 0.6 megapixels (1024 x 640 pixels) would consume 5 GB VRAM. What could we do to reduce the VRAM requirements? Is this relationship linear with size of the image?

**Comment by sunwj** [comment]
May be you can split your large image into slightly overlapping patches, then super-resolve those patches seperately, and finally combine those patches together.
