### ISSUE TITLE
DIV2K val x4 psnr only 23.86......

### ISSUE THREAD

**Issue by zhangqizky** [sunwj/CAR#23]
Hi,
I use the model you release to test div2k val x4, but got a psnr of 23.86, which is not consistent with the benchmark in paperwithcode net.....Do I use wrong model?
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/23207132/176370176-1976d910-49c4-46d2-be3c-b5448839aa29.png">

**Comment by sunwj** [comment]
We have tested the running script on DIV2K validation set and obtained correct results.

**Comment by zhangqizky** [comment]
你们这个32.82的结果是 用DIV2K官方released的 x4 LQ输入，然后用你们放出来的usn.pth那个EDSR去跑的吗？
