### ISSUE TITLE
No gridsampler backward function

### ISSUE THREAD

**Issue by pierrecournutmwm** [sunwj/CAR#5]
Hi,
Thank you for posting your code, downscaling and upscaling result images are really neat!  
However, the gridsampler CUDA extension lacks a backward method. Could you please release it?

**Comment by miniagarwal09** [comment]
I also do need it for my research work, please release the backward function code, it will be really helpful...

**Comment by yuqian2019** [comment]
> I also do need it for my research work, please release the backward function code, it will be really helpful...
Do u got the train code？

**Comment by miniagarwal09** [comment]
> > I also do need it for my research work, please release the backward function code, it will be really helpful...
> > Do u got the train code？

No

**Comment by yuqian2019** [comment]
> > > I also do need it for my research work, please release the backward function code, it will be really helpful...
> > > Do u got the train code？
> 
> No

ok, I had find the backward propagation process had mentioned in paper, do u try to recovery it? If u need, maybe we can together to recover the backward propagation process.

**Comment by miniagarwal09** [comment]
> > > > I also do need it for my research work, please release the backward function code, it will be really helpful...
> > > > Do u got the train code？
> > 
> > 
> > No
> 
> ok, I have found the backward propagation process had mentioned in paper, do u try to reproduce it? If u need, maybe we can together to reproduce the backward propagation process.

I tried that, but have to no idea how exactly does the backward function work and not many examples are present online.

**Comment by sunwj** [comment]
backward code is available
